{{- if eq .Values.global.secretStore.backend "kubernetes" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-backend
  namespace: external-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.ocpExternalSecrets.kubernetes.remoteNamespace }}
      server:
        url: {{ .Values.ocpExternalSecrets.kubernetes.server.url }}
{{- if .Values.ocpExternalSecrets.caProvider.enabled }}
{{- if .Values.clusterGroup.isHubCluster }}
        caProvider:
          type: {{ .Values.ocpExternalSecrets.caProvider.hostCluster.type }}
          name: {{ .Values.ocpExternalSecrets.caProvider.hostCluster.name }}
          key: {{ .Values.ocpExternalSecrets.caProvider.hostCluster.key }}
          namespace: {{ .Values.ocpExternalSecrets.caProvider.hostCluster.namespace }}
{{- else }}
        caProvider:
          type: {{ .Values.ocpExternalSecrets.caProvider.clientCluster.type }}
          name: {{ .Values.ocpExternalSecrets.caProvider.clientCluster.name }}
          key: {{ .Values.ocpExternalSecrets.caProvider.clientCluster.key }}
          namespace: {{ .Values.ocpExternalSecrets.caProvider.clientCluster.namespace }}
{{- end }}
{{- end }}
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
{{- end }}
