apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  labels:
    app.kubernetes.io/name: external-secrets-operator
  name: cluster
spec:
  controllerConfig:
    networkPolicies:
    - name: allow-vault-access
      componentName: ExternalSecretsCoreController
      egress:
      - ports:
        - protocol: TCP
          port: 443   # HTTPS port for route access
